### ISSUE TITLE
Importing custom properties from another package

### ISSUE THREAD

**Issue by the-spyke** [csstools/postcss-preset-env#37] opened 2018-06-05 12:06 UTC
I have a Webpack setup with `postcss-loader`, `postcss-import`, and `postcss-preset-env`. I also have a separate npm package with my theme: a bunch of `.css` files with variables.

In CSS files for various components (React + CSS Modules) I import the theme like this: `@import "my-theme/variables.css";`

The issue that I have right now is that all those variables are duplicated many times in the output CSS file. I assume it should be include only once the first time it was imported.

Am I doing something wrong?

**Comment by jonathantneal** [comment] 2018-06-05 18:46
Hi @the-spyke,

You should not be seeing multiple `:root {}` depending upon how you are importing those variables.

@pascalduez, in regular `postcss-import` usage, duplication should not occur:

> In order to optimize output, [PostCSS Import] will only import a file once on a given scope (root, media query...). Tests are made from the path & the content of imported files (using a hash table). If this behavior is not what you want, look at skipDuplicates option

@the-spyke, if you could create a small, reproducible version of this issue, I would be happy to look into it. However, since this plugin does not duplicate custom property declarations (because the postcss-custom-properties does not do this by default), I am closing this issue.

Again, I’m still listening, though.

**Comment by pascalduez** [comment] 2018-06-05 20:24
> in regular postcss-import usage, duplication should not occur:

I believe in a CSS modules context a new PostCSS instance is run per module (file) and in such it's not aware of the other modules, hence duplication.
I haven't tested it for a while though.

**Comment by the-spyke** [comment] 2018-06-12 08:05
Actually, I see duplication even in case of same package imports.

@jonathantneal Here is my example: https://github.com/the-spyke/postcss-duplication

**Comment by bhardy** [comment] 2018-07-06 23:19
@jonathantneal we are also having this exact issue. @the-spyke's example looks to be identical to what we're seeing in our project. I don't know that it's an issue with `postcss-preset-env`, more likely it's `postcss-import`. I tested with `cssnext` and had the same issue.

**Comment by jonathantneal** [comment] 2018-07-06 23:20
Thanks for these links. I didn’t catch @the-spyke’s update, and I will look into this.

**Comment by bhardy** [comment] 2018-07-06 23:44
@jonathantneal FYI if we set `customProperties`'s `preserve` to false it won't duplicate the `:root`.

**Comment by bhardy** [comment] 2018-08-19 17:57
@shimingw yes, that will fix this current issue but you'll lose the benefit of the custom properties in browsers that support them. This could be an issue in a case where you're doing "graceful degradation" (do people still say that?). For example, we wanted to do theming by simply overriding css custom properties and then just not have the themes work in IE11—this won't work with `preserve: false`

**Comment by pascalduez** [comment] 2018-08-20 05:41
It's not an issue with `postcss-preset-env` has I [mentioned earlier](https://github.com/csstools/postcss-preset-env/issues/37#issuecomment-394782227). 
Webpack's `postcss-loader` process CSS file by file, thus import the variables in every files.
Then the `MiniCssExtractPlugin` concat all files. 

One possible solution is defining the variables in JS instead, through the `variables` options of `postcss-custom-properties`.

**Comment by bhardy** [comment] 2018-08-27 20:32
@pascalduez there are definitely a few workarounds to get this working in production as is. I believe the issue is that we want to allow developers to leverage custom properties (in CSS modules) in browsers that support them while delivering a non-broken solution to IE11.

**Comment by pascalduez** [comment] 2018-08-27 22:45
> I believe the issue is that we want to allow developers to leverage custom properties (in CSS modules) in browsers that support them while delivering a non-broken solution to IE11.

That what I mean too. As soon as you `preserve` the custom properties, their declarations will get duplicated in every module.

**Comment by jonathantneal** [comment] 2018-09-18 16:54
Resolving via https://github.com/csstools/postcss-preset-env/pull/73

You will be able to reference external files with Custom Properties, Custom Selectors, and Custom Media using the `importFrom` and `exportTo` features available to each of those plugins.

In v6, I will forward these from preset-env options to each plugin.

**Closed by jonathantneal** 2018-09-18 16:54 UTC
