### ISSUE TITLE
Custom media not working in dynamic imports

### ISSUE THREAD

**Issue by dangerhire8** [csstools/postcss-preset-env#136] opened 2019-06-19 15:06 UTC
In my main entry point all works fine, but css in splitted chunks that has been registered like this
`chunkName: () => import( /* webpackChunkName: "chunkName" */ '/js/chunks/chunkName'),` - not.

In splitted css file media queries looks like this
```...
@media(--sm-only) {.some{
    padding: 0 15px
}
```

postcss.config.js:
```
module.exports = {
    plugins: {
        'postcss-import': {},
        'postcss-mixins': {},
        'postcss-nested': {},
        'postcss-preset-env': {
            stage: 1,
            autoprefixer: { grid: true },
            preserve: false
        }
    }
};
```

webpack.config.js:

```
rules: [
            {
                test: /\.css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    'postcss-loader'
                ]
            }
       ]
```

for dynamyc imports I'm using `@babel/plugin-syntax-dynamic-import`.

Any ideas it's mine fault or plugin error ?

**Comment by jonathantneal** [comment] 2019-09-05 19:04
Would you please create a repository with the most reduced possible example? From there, I may be able to help you debug this, and resolve any issues with the project or its sub-projects.

**Comment by romainmenke** [comment] 2021-12-22 11:45
@dangerhire8 This repo has been moved to https://github.com/csstools/postcss-plugins

Could you open a new issue with reproduction details (preferable a github repo) there?
It is possible that this has been resolved in the mean time.

Going to close this issue because we will archive this repo which makes further discussion here impossible.

**Closed by romainmenke** 2021-12-22 11:45 UTC
Labels: help wanted, feedback requested
