### ISSUE TITLE
-webkit-calc breaks environment-variables

### ISSUE THREAD

**Issue by natecox** [csstools/postcss-preset-env#126] opened 2019-05-21 17:53 UTC
#### Overview
While integrating a third party toaster notification library into my project, I came across a bug involving `-webkit-calc` which prevents compiling.

#### Details
After adding the [Noty.js](https://ned.im/noty/) toaster library onto my project, I started getting failures to compile CSS. After a deep dive into what was happening, I realized that the CSS file being provided from the project had been pre-compiled with autoprefixer, and several lines where `calc()` was used were resulting in a duplicate `-webkit-calc()`. This prefixed version breaks the custom environment variables feature for an unknown reason.

I managed to eliminate all of the other vendor prefixes included in their output file by manually removing them; all of the vendor prefixes except for `-webkit-calc()` work fine. I suspect that this is because the other instances were a part of the CSS property, rather than the value, but I have no basis for that other than random observation.

#### Demo
Here's a [quick codepen example](https://codepen.io/natecox/pen/OYOOWm) of the problem. I've made it as bare-bones as possible. You'll notice that the postcss is failing:
![image](https://user-images.githubusercontent.com/2782695/58118823-852b9100-7bb6-11e9-817f-a60fccbdff33.png)

Removing `-webkit-` from the `calc()` usage will cause the css to compile normally.

*EDIT*
I should note that I narrowed this down to environment variables by moving to stage 1 and seeing success, then adding the environment variables feature individually to see it fail. Nesting rules does not cause an error.

**Comment by koresar** [comment] 2019-05-24 09:01
I found the cause. Here is the solution: https://github.com/postcss/postcss-custom-properties/issues/161

Upgrade to postcss-values-parser@3.

Hey, @jonathantneal could you please `npm i -S postcss-values-parser@3` and publish a v6.6.1?

**Comment by romainmenke** [comment] 2021-12-22 11:41
@natecox Thank you for reporting this.

We migrated everything to `postcss-value-parser` and we can no longer reproduce this issue.
It should be resolved by updating to the latest versions.

**Closed by romainmenke** 2021-12-22 11:41 UTC
