### ISSUE TITLE
Unwanted appending to `inline` class names

### ISSUE THREAD

**Issue by findoo** [csstools/postcss-preset-env#116] opened 2019-02-21 15:44 UTC
When using postcss-preset-env in combination with the `rollup-plugin-postcss` we are finding odd behaviour when you call a class `inline`.

CSS - 
`.inline {
    color: red;
}`

Leads to an object containing -
`{ inline-left: 'inline', inline-right: 'inline' }`
when the file is imported.

See example project to reproduce https://github.com/findoo/PostCSS-Inline-Bug

**Comment by jonathantneal** [comment] 2019-02-21 15:54
There are not any plugins in this project that transform selectors this way. Thanks for setting up a project for me to look into it, but I would also look outside PostCSS for whatever is causing this.

**Comment by findoo** [comment] 2019-02-21 15:57
@jonathantneal could very well be `rollup-plugin-postcss` causing the problem, I'm not sure - really appreciate you looking into it 😄
The only difference between the bugged config and the working one in that project, is the inclusion of `postcss-preset-env`

**Comment by emjaksa** [comment] 2019-05-02 09:15
I am having the same issue. It seems to be a combination of using both css-modules in the `rollup-plugin-postcss` plugin and `postcss-preset-env`. When I disable one of them it works fine.

**Comment by emjaksa** [comment] 2019-05-02 09:43
Narrowed it down to the following `postcss-logical` plugin in `postcss-preset-env`. When I disable that plugin it works. 

```
postcssPresetEnv({
  features: {
    'logical-properties-and-values': false,
  },
}),
```

**Comment by jonathantneal** [comment] 2019-09-05 19:18
@emjaksa, does this occur when using the latest logical plugin all by itself? https://github.com/csstools/postcss-logical

This seems like an issue with how `rollup-plugin-postcss` exposes the AST to the plugin.

**Comment by romainmenke** [comment] 2021-12-22 11:06
This is no longer reproducible with the latest versions of all dependencies.
Was likely fixed in `rollup-plugin-postcss`

**Closed by romainmenke** 2021-12-22 11:06 UTC
Labels: feedback requested
