### ISSUE TITLE
place-content/items issue 

### ISSUE THREAD

**Issue by nevolgograd** [csstools/postcss-preset-env#229] opened 2021-11-26 09:14 UTC
I have simple webpack/postcss stack and my build is failing each time I use `place-content` or `place-items` properties

**Here’s the error:**
```
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading 'includes')
```

I'm using latest version of the package:
```
"postcss-preset-env": "^7.0.1",
```

**PostCSS config:**
```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-normalize'),
    require('postcss-color-mod-function'),
    require('postcss-preset-env')
  ]
};
```

**Webpack config:**
```
{
  test: /\.(scss|css)$/,
  use: [
    {
      loader: 'css-loader',
      options: {
        modules: true,
        importLoaders: 1
      }
    },
    {
      loader: 'postcss-loader'
    },
    {
      loader: 'sass-loader'
    }
  ]
}
```

I will be grateful for any advice!

**Comment by Antonio-Laguna** [comment] 2021-11-26 09:25
Does any minimal code fail with that?

**Comment by nevolgograd** [comment] 2021-11-26 09:35
@Antonio-Laguna 

I can have only css file which i import in my entry and still getting same error

`import 'styles/main.css';`

```
:global {
  body {
    place-content: center;
  }
}
```

**Comment by Antonio-Laguna** [comment] 2021-11-26 09:36
Thanks! Can you tell me your node version? @nevolgograd

**Comment by nevolgograd** [comment] 2021-11-26 09:37
@Antonio-Laguna  `v16.13.0`

**Comment by Antonio-Laguna** [comment] 2021-11-26 10:41
@nevolgograd would it be possible to have access to your repo? This issue is similar as #225 but I'm having a hard time reproducing this.

I've created two files: `index.css` and `main.css`, within `main.css` I've put 

```css
:global {
  body {
    place-content: center;
  }
}
```

Then on `index.css` this is the only thing `@import 'main.css';`

The `postcss.config.js` file is like this:

```js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-normalize'),
    require('postcss-color-mod-function'),
    require('postcss-preset-env')
  ]
};
```

Ran with `postcss-cli` like `npx postcss src/index.css -o dist/output.css` and had a successful output so I'm not sure what I'm missing.

**Comment by nevolgograd** [comment] 2021-11-26 11:50
@Antonio-Laguna thanks! My repo is private, but i'll create a copy in a moment.

**Comment by nevolgograd** [comment] 2021-11-26 11:52
@Antonio-Laguna [https://github.com/nevolgograd/postcss-config-hell](url)

**Comment by Antonio-Laguna** [comment] 2021-11-26 12:08
Thanks for preparing this @nevolgograd ! I'll take a look soon and update you on this.

**Comment by Antonio-Laguna** [comment] 2021-11-26 12:26
Can reproduce here at least. What I can see is that this is mixing some postcss versions which isn't fine. 

All of our plugins use `postcss 8` but we got `postcss@7.0.39` and `postcss@6.0.23` too. This all seems to come from `typescript-plugin-css-modules` which uses things such as `postcss-filter-plugins` which are not upgraded to use PostCSS 8.

I'll dig a bit more to see if this is coming from our code and if it's something we could prevent.

**Comment by armano2** [comment] 2021-11-26 12:31
nooo, issue is somewhere else, it seem that enabling `postcss-lab-function` after `postcss-place` leads to 
```css
  align-content: undefined;
  justify-content: undefined;
  place-content: center;
```

and crash comes from `autoprefixer`

----
repro

```js
// postcss.config.js
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('postcss-lab-function'),
    require('postcss-place')({}),
  ]
};
```

```css
/* index.css */
body {
  place-content: center;
}
```

**Comment by Antonio-Laguna** [comment] 2021-11-26 12:46
@armano2 can't seem to repro with your use case. Seems to output just fine for me, no `undefined` :/

**Comment by armano2** [comment] 2021-11-26 12:49
> @armano2 can't seem to repro with your use case. Seems to output just fine for me, no `undefined` :/

https://github.com/armano2/postcss-config-hell/runs/4334066139?check_suite_focus=true

**Comment by Antonio-Laguna** [comment] 2021-11-26 12:52
Thanks! Will check what was different but can repro on your fork!

**Comment by armano2** [comment] 2021-11-26 13:18
`npm dedupe` seem to be solving this issue

this seem to be related to `postcss-values-parser` being incorrectly hoisted

**Comment by Antonio-Laguna** [comment] 2021-11-26 13:23
Thanks for investigating. That's probably why I don't get the error on my test case but happens here 

Probably related to #229

**Comment by evenfrost** [comment] 2021-11-26 16:44
FYI, Tailwind CSS build fails because of that as well, due to `@tailwind utilities;` using this declaration internally. Looking forward to a fix, but for now `npm i postcss-preset-env@6`.

**Comment by Antonio-Laguna** [comment] 2021-11-26 18:13
@evenfrost what package is using `@tailwind utilities`? Could you point me at that?

**Comment by evenfrost** [comment] 2021-12-10 16:09
@Antonio-Laguna sorry for the late reply. It's [Tailwind CSS](https://tailwindcss.com/).

**Comment by Antonio-Laguna** [comment] 2021-12-16 10:24
This should now be fixed as of https://github.com/csstools/postcss-plugins/commit/b1c4d2768179ba0d3e1f2b38e295ce8e908fa242 

@nevolgograd I'd appreciate a lot if you could bump to `7.0.2` and see if it goes well

**Comment by nevolgograd** [comment] 2021-12-23 10:40
@Antonio-Laguna since then i've changed a lot in my code, basically i removed `postcss-color-mod-function` plugin and it worked for me even on prev version. 
`v7.1.0` works good as well.

**Comment by Antonio-Laguna** [comment] 2021-12-23 10:54
Great! Thanks! Closing this issue then!

**Closed by Antonio-Laguna** 2021-12-23 10:54 UTC
