### ISSUE TITLE
Not functioning for me

### ISSUE THREAD

**Issue by finom** [csstools/postcss-preset-env#42] opened 2018-06-20 23:40 UTC
I use the preset with Webpack but it doesn't seem functioning:

```
plugins: wp => [
  postcssPresetEnv({
    stage: 0,
  }),
  importPlugin({
    load: postCSSImportLoadJSHook(),
    addDependencyTo: wp,
    resolve(id, basedir) {
      return resolver.resolveSync({}, basedir, id);
    },
  }),
]
```

At the project I develop I tried to replace `postcss-cssnext` which was fully functioning. I also tried to use other plugins (like postcss-custom-properties) which worked fine. I tried to move `postcssPresetEnv` call to the top and to the bottom of the plugin list and it didn't help. Tried to use different options: features and stages...

By saying "not functioning" I mean it doesn't change CSS at all: nested rules, custom selectors and stuff. I know that the description isn't really informational and by creating this issue I'd ask you to help me to find what's gone wrong. Thank you.

**Comment by finom** [comment] 2018-06-21 00:04
OMG, there is how it's worked. Copy-pasted some code from the project source:

```

const idsByExecutionOrder  = [
	'custom-properties',
	'custom-property-sets',
	'image-set-function',
	'logical-properties-and-values',
	'nesting-rules',
	'custom-media-queries',
	'media-query-ranges',
	'custom-selectors',
	'case-insensitive-attributes',
	'rebeccapurple-color',
	'hexadecimal-alpha-notation',
	'lab-function',
	'color-mod-function',
	'color-functional-notation',
	'system-ui-font-family',
	'font-variant-property',
	'all-property',
	'matches-pseudo-class',
	'not-pseudo-class',
	'any-link-pseudo-class',
	'dir-pseudo-class',
	'break-properties',
	'gap-properties',
	'overflow-property',
	'overflow-wrap-property',
	'place-properties',
	'focus-visible-pseudo-class',
	'focus-within-pseudo-class'
];

import postcssAttributeCaseInsensitive from 'postcss-attribute-case-insensitive';
import postcssColorFunctionalNotation from 'postcss-color-functional-notation';
import postcssColorHexAlpha from 'postcss-color-hex-alpha';
import postcssColorModFunction from 'postcss-color-mod-function';
import postcssColorRebeccapurple from 'postcss-color-rebeccapurple';
import postcssCustomMedia from 'postcss-custom-media';
import postcssCustomProperties from 'postcss-custom-properties';
import postcssCustomSelectors from 'postcss-custom-selectors';
import postcssDirPseudoClass from 'postcss-dir-pseudo-class';
import postcssFocusVisible from 'postcss-focus-visible';
import postcssFocusWithin from 'postcss-focus-within';
import postcssFontVariant from 'postcss-font-variant';
import postcssFontFamilySystemUi from 'postcss-font-family-system-ui';
import postcssGapProperties from 'postcss-gap-properties';
import postcssImageSetPolyfill from 'postcss-image-set-function';
import postcssInitial from 'postcss-initial';
import postcssLabFunction from 'postcss-lab-function';
import postcssLogical from 'postcss-logical';
import postcssMediaMinmax from 'postcss-media-minmax';
import postcssNesting from 'postcss-nesting';
import postcssOverflowShorthand from 'postcss-overflow-shorthand';
import postcssPageBreak from 'postcss-page-break';
import postcssPlace from 'postcss-place';
import postcssPseudoClassAnyLink from 'postcss-pseudo-class-any-link';
import postcssReplaceOverflowWrap from 'postcss-replace-overflow-wrap';
import postcssSelectorMatches from 'postcss-selector-matches';
import postcssSelectorNot from 'postcss-selector-not';

// postcss plugins ordered by id
const pluginsById =  {
	'all-property': postcssInitial,
	'any-link-pseudo-class': postcssPseudoClassAnyLink,
	'break-properties': postcssPageBreak,
	'case-insensitive-attributes': postcssAttributeCaseInsensitive,
	'color-functional-notation': postcssColorFunctionalNotation,
	'color-mod-function': postcssColorModFunction,
	'custom-media-queries': postcssCustomMedia,
	'custom-properties': postcssCustomProperties,
	'custom-selectors': postcssCustomSelectors,
	'dir-pseudo-class': postcssDirPseudoClass,
	'focus-visible-pseudo-class': postcssFocusVisible,
	'focus-within-pseudo-class': postcssFocusWithin,
	'font-variant-property': postcssFontVariant,
	'gap-properties': postcssGapProperties,
	'hexadecimal-alpha-notation': postcssColorHexAlpha,
	'image-set-function': postcssImageSetPolyfill,
	'lab-function': postcssLabFunction,
	'logical-properties-and-values': postcssLogical,
	'matches-pseudo-class': postcssSelectorMatches,
	'media-query-ranges': postcssMediaMinmax,
	'nesting-rules': postcssNesting,
	'not-pseudo-class': postcssSelectorNot,
	'overflow-property': postcssOverflowShorthand,
	'overflow-wrap-property': postcssReplaceOverflowWrap,
	'place-properties': postcssPlace,
	'rebeccapurple-color': postcssColorRebeccapurple,
	'system-ui-font-family': postcssFontFamilySystemUi
};

...

wp => [
  importPlugin({
    load: postCSSImportLoadJSHook(),
    addDependencyTo: wp,
    resolve(id, basedir) {
      return resolver.resolveSync({}, basedir, id);
    },
  }),
  applyPlugin(),
  ...idsByExecutionOrder.filter(id => pluginsById[id]).map(id => pluginsById[id]),
]
```

Anyway the question still open.

**Comment by jonathantneal** [comment] 2018-06-21 16:23
Could you put a reduced test case on GitHub for me to debug? Otherwise, I may not have enough information to help you.

**Comment by finom** [comment] 2018-06-21 16:28
@jonathantneal excuse me but I was completely blocked and decided to use children plugins instead of postcss-preset-env. The issue isn't actual for me 😐
Thank you for the response.

**Comment by jonathantneal** [comment] 2018-06-21 16:32
I’m sorry you had an issue, and that the issue isn’t actually for you which I presume means I should close this? I’m glad you have something going, but I would prefer you used the preset so you aren’t unnecessarily changing CSS.

**Closed by jonathantneal** 2018-06-21 16:32 UTC
