### ISSUE TITLE
Support PostCSS 8

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env#191] opened 2020-09-15 17:16 UTC
Hey, neat project. I did notice this is still running PostCSS 7. I also saw that it hasn’t had a commit since April. Did you have a chance to see that PostCSS 8 is out? The creators of the project have even released this [migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration).

- Can we expect support for PostCSS 8?
- Are you still working on the project?
- Can I help? 😄 

Oh wait hold up I’m me. Umm...

- Yes!
- Yes, tho proof must be in the pudding.
- Of course.

**Comment by Semigradsky** [comment] 2020-09-15 19:01
I will be happy to help 😸

**Comment by Semigradsky** [comment] 2020-09-16 09:43
| Plugin | Ready for Postcss 8 | Note |
|--------|---------------------|------|
| [css-blank-pseudo](https://github.com/csstools/css-blank-pseudo) | | Plugin require JS |
| [css-has-pseudo](https://github.com/csstools/css-has-pseudo) | | Plugin require JS |
| [css-prefers-color-scheme](https://github.com/csstools/css-prefers-color-scheme) | | Plugin require JS |
| [postcss-attribute-case-insensitive](https://github.com/Semigradsky/postcss-attribute-case-insensitive) | Ready - v5.0.0 | |
| [postcss-color-functional-notation](https://www.npmjs.com/package/postcss-color-functional-notation) | | |
| [postcss-color-gray](https://www.npmjs.com/package/postcss-color-gray) | | Was removed from Spec - candidate for removing? |
| [postcss-color-hex-alpha](https://github.com/postcss/postcss-color-hex-alpha) | | |
| [postcss-color-mod-function](https://github.com/jonathantneal/postcss-color-mod-function) | | Was removed from Spec - candidate for removing? |
| [postcss-color-rebeccapurple](https://github.com/postcss/postcss-color-rebeccapurple) | | [96.74% browser support](https://caniuse.com/css-rebeccapurple) - candidate for removing? |
| [postcss-custom-media](https://github.com/postcss/postcss-custom-media) | | |
| [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) | | |
| [postcss-custom-selectors](https://github.com/postcss/postcss-custom-selectors) | | |
| [postcss-dir-pseudo-class](https://github.com/jonathantneal/postcss-dir-pseudo-class) | | |
| [postcss-double-position-gradients](https://github.com/csstools/postcss-double-position-gradients) | | |
| [postcss-env-function](https://github.com/csstools/postcss-env-function) | | |
| [postcss-focus-visible](https://github.com/csstools/postcss-focus-visible) | | Plugin require JS |
| [postcss-focus-within](https://github.com/csstools/postcss-focus-within) | | Plugin require JS |
| [postcss-font-family-system-ui](https://github.com/JLHwung/postcss-font-family-system-ui) | https://github.com/JLHwung/postcss-font-family-system-ui/issues/326 | Currently `postcss-preset-env` use 'fork' |
| [postcss-font-variant](https://github.com/postcss/postcss-font-variant) | | |
| [postcss-gap-properties](https://github.com/jonathantneal/postcss-gap-properties) | | |
| [postcss-image-set-function](https://github.com/csstools/postcss-image-set-function) | | |
| [postcss-initial](https://github.com/maximkoretskiy/postcss-initial) | https://github.com/maximkoretskiy/postcss-initial/issues/39 | [96.23% browser support](https://caniuse.com/css-initial-value) - candidate for removing? |
| [postcss-lab-function](https://github.com/csstools/postcss-lab-function) | | |
| [postcss-logical](https://github.com/csstools/postcss-logical) | | |
| [postcss-media-minmax](https://github.com/postcss/postcss-media-minmax) | | |
| [postcss-nesting](https://github.com/jonathantneal/postcss-nesting) | | |
| [postcss-overflow-shorthand](https://github.com/jonathantneal/postcss-overflow-shorthand) | | |
| [postcss-page-break](https://github.com/shrpne/postcss-page-break) | | |
| [postcss-place](https://github.com/csstools/postcss-place) | | |
| [postcss-pseudo-class-any-link](https://github.com/jonathantneal/postcss-pseudo-class-any-link) | | [95.06% browser support]() - candidate for removing? |
| [postcss-replace-overflow-wrap](https://github.com/MattDiMu/postcss-replace-overflow-wrap) | https://github.com/MattDiMu/postcss-replace-overflow-wrap/issues/9 | [98.76 browser support](https://caniuse.com/wordwrap) - candidate for removing? |
| [postcss-selector-matches](https://github.com/postcss/postcss-selector-matches) | | `:mathes` was renamed to `:is` and incorrectly implemented - candidate for removing? |
| [postcss-selector-not](https://github.com/postcss/postcss-selector-not) | | |

**Comment by Semigradsky** [comment] 2020-09-16 09:58
Candidates for adding
| Plugin | Ready for Postcss 8 | Note |
|--------|---------------------|------|
| [postcss-font-format-keywords](https://github.com/valtlai/postcss-font-format-keywords) | https://github.com/valtlai/postcss-font-format-keywords/issues/2 | |
| [postcss-clamp](https://github.com/polemius/postcss-clamp) | https://github.com/polemius/postcss-clamp/issues/2 | |
| [postcss-normalize-display-values](https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-display-values) | https://github.com/cssnano/cssnano/issues/952 | |
| [postcss-ic-unit](https://github.com/JLHwung/postcss-ic-unit) | https://github.com/JLHwung/postcss-ic-unit/issues/36 | |

**Comment by JLHwung** [comment] 2020-09-16 16:09
Note that it is also blocked by an upstream `postcss-tape` issue: https://github.com/csstools/postcss-tape/issues/5

**Comment by goto-bus-stop** [comment] 2020-09-19 10:41
PR for postcss-color-hex-alpha: https://github.com/postcss/postcss-color-hex-alpha/pull/15

**Comment by heath-freenome** [comment] 2020-10-23 18:37
How close are you to making the simplest update possible ready (i.e. just porting to the `Root()` syntax), then doing the hard work of switching to using the `Rule()`, `AtRule()`, etc... later?

**Comment by solidevolution** [comment] 2021-02-03 08:57
Are there any updates?

**Comment by Semigradsky** [comment] 2021-02-03 10:40
@solidevolution see https://github.com/csstools/postcss-preset-env/issues/191#issuecomment-693295774

If you'd like to help you can open a PR in any repo that doesn't already have PostCSS8 support or review existing PRs.

**Comment by Airkro** [comment] 2021-02-23 07:12
I didn't see "how to create a preset" in 8.x migration guide.

**Comment by pi0** [comment] 2021-03-05 12:42
Hi @jonathantneal. Would you please confirm if above table is updated?

**Comment by armano2** [comment] 2021-03-12 02:54
@Semigradsky postcss-gap-properties - https://github.com/jonathantneal/postcss-gap-properties/pull/4

**Comment by armano2** [comment] 2021-03-12 19:04
update:
`postcss-double-position-gradients` - https://github.com/csstools/postcss-double-position-gradients/pull/2

**Comment by armano2** [comment] 2021-03-13 18:22
`postcss-pseudo-class-any-link` - https://github.com/jonathantneal/postcss-pseudo-class-any-link/pull/11

**Comment by armano2** [comment] 2021-03-20 07:22
is there anything else that has to be done to proceed with support for postcss 8?

**Comment by ludofischer** [comment] 2021-03-22 13:58
> is there anything else that has to be done to proceed with support for postcss 8?

PostCSS 7 plugins should run under PostCSS 8 (they just emit a warning), so you don't require every plugin to migrate to use it with PostCSS 8.

**Comment by armano2** [comment] 2021-03-22 14:36
@ludofischer all plugins have hard dependency on postcss 7

**Comment by ludofischer** [comment] 2021-03-22 14:40
> @ludofischer all plugins have hard dependency on postcss 7

All PostCSS 7 plugins do, but you can still run them with PostCSS 8. Porting everything to PostCSS 8 is necessary only to get rid of duplicate PostCSS in `node_modules`.

**Comment by armano2** [comment] 2021-03-22 14:43
in many cases it lets to hoisting issues that prevent consumers to actually run it

e.g. 
https://github.com/facebook/docusaurus/issues/4378
https://github.com/facebook/docusaurus/pull/4404/checks?check_run_id=2091632671

**Comment by lostfictions** [comment] 2021-04-12 06:28
This is a common issue when using Tailwind and/or NextJS as well:

**Comment by wommy** [comment] 2021-05-01 01:11
im willing to help,

can we set up something in the project tab?

**Comment by JohnAlbin** [comment] 2021-05-10 16:19
First off, I love this tool. Thanks so much for making it and maintaining it!

> All PostCSS 7 plugins do, but you can still run them with PostCSS 8. Porting everything to PostCSS 8 is necessary only to get rid of duplicate PostCSS in node_modules.

That's not correct. PostCSS v8 plugins can be incompatible with PostCSS v7 plugins. Both plugins will "work" with PostCSS v8, but those plugins may not work together properly.

@Semigradsky Postcss-nesting has been marked as "complete", but the API conversion was only partially completed (at least I assume that's why it is misbehaving with other PostCSS v8 plugins). See https://github.com/csstools/postcss-nesting/issues/83

**Comment by crooksey** [comment] 2021-05-20 10:47
@Semigradsky great work on this, so far to get an update as of 20/05/2021 it looks like other than awaiting various PR's to be merged, we just need to potentially remove "postcss-color-mod-function" from this library as support for it has been dropped?

**Comment by almothafar** [comment] 2021-05-30 10:45
Is this repo already dead or something?

**Comment by hitendra-ap** [comment] 2021-06-07 13:02
Hi, Is this still alive? Any idea when it is moving in?

**Comment by almothafar** [comment] 2021-06-07 13:20
> Hi, Is this still alive? Any idea when it is moving in?

When I asked this question, I got a lot of -1's without anyone bothering to write any answer, so good luck with that 😅

**Comment by ehoogeveen-medweb** [comment] 2021-06-07 13:38
A lot of work has been done here to update all the dependencies - the problem is that the pull requests in the dependencies aren't being merged as some of them appear to be abandoned.

Maybe there's more that can be done to reach out to the maintainers of those repos and offer to take over. Otherwise I think the only way forward is to fork the dependencies or (temporarily) incorporate updated versions into this repo.

**Comment by Airkro** [comment] 2021-06-07 15:27
An open-source project(mostly without a team) is impossible to answer "when". we have to get used to it.

For anyone who can't wait: Make your lite version fork, it's easy, and safer(select features you actually needed).

My version: https://github.com/best-shot/postcss-preset-evergreen

**Comment by jonathantneal** [comment] 2021-06-11 21:06
> Maybe there's more that can be done to reach out to the maintainers of those repos and offer to take over

I am the maintainer of those repos. 😅

**Comment by jonathantneal** [comment] 2021-06-11 21:14
> I got a lot of -1's without anyone bothering to write any answer

What a bummer. They should -1 me, not you. I never expected to run out of free time. I never expected to get so blocked parsing values that I would have to write my own parser, which mean writing my own parser, which meant writing my own tokenizer, which meant learning how css is tokenized, which meant learning what tokenization is.

And then somebody hits me up about container queries or tab components and how we can help spread adoption, and I spend a few hours helping out there, while this slips further. It’s so awful. I want to do my best, and it takes such a big chunk of time.

I’ve never stopped trying to make a way for all of this to be updated. Believe me, for nearly two years I haven’t been at ease when I know my weekend has some free time, and I won’t be until it’s finished.

**Comment by romainmenke** [comment] 2021-06-11 21:24
@jonathantneal What can we do to help?

**Comment by jonathantneal** [comment] 2021-06-11 21:52
The most realistic help would be getting ourselves into a Discord channel where we could manage this with higher touch. Basically, I want to be more responsive to contributors and the community. And, at worst, I want to be more annoyed, so that it’s top of mind and gets done much sooner.

We could use a chat room to coordinate updating the plugins I’ve neglected to notice are ready to be published or have PRs ready to get them up to speed. We kinda did that here, but it eventually got threaded into email. It also helps to do this in the open, to show good faith to users. I think it also helps to do this in the open, so people can get connected with each other.

So, please, anything that is more alive than email. Over email, things often get lost, because I maintain roughly 114 css tools, almost all postcss plugins, not including the ones I maintain in the postcss repos, or the ones that require client-side polyfills that live under my username or jsxtools.

**Comment by niksy** [comment] 2021-06-12 09:57
> The most realistic help would be getting ourselves into a Discord channel where we could manage this with higher touch.

Should we start here?

**Comment by crooksey** [comment] 2021-06-14 06:21
@jonathantneal  I created a gitter channel? Sent you an invite, if you are OK with this, I will post the link here.

**Comment by jonathantneal** [comment] 2021-06-14 12:48
I can keep up with Discord and Slack. Here’s an invite link for anyone willing to help.

https://discord.gg/JTHpyexU

**Comment by zleight1** [comment] 2021-07-13 14:33
> I can keep up with Discord and Slack. Here’s an invite link for anyone willing to help.
> 
> https://discord.gg/JTHpyexU

Looks like this invite expired

**Comment by crooksey** [comment] 2021-07-15 09:04
> > I can keep up with Discord and Slack. Here’s an invite link for anyone willing to help.
> > https://discord.gg/JTHpyexU
> 
> Looks like this invite expired

https://discord.gg/9GZNpqXR

**Comment by Antonio-Laguna** [comment] 2021-07-27 10:11
Happened again. Can't join. Is there anything I can do to help?

**Comment by xithalius** [comment] 2021-07-27 16:19
> Happened again. Can't join. Is there anything I can do to help?

This link won't expire: https://discord.gg/8wHumqgb9r

**Comment by mikestopcontinues** [comment] 2021-08-21 16:51
@Semigradsky It's been about a month since your last chart update. Are we close? 👀

**Comment by Semigradsky** [comment] 2021-08-28 13:35
@mikestopcontinues as I see there is nothing new: the PRs have been merged, but there have been no new releases.
@jonathantneal could you give me access to npm for these packages or release them himself?

**Comment by dargmuesli** [comment] 2021-09-16 16:51
@Semigradsky we've managed to release css-blank-pseudo and css-has-pseudo today. Other releases are going to follow in the coming days.

**Comment by dargmuesli** [comment] 2021-09-22 15:15
All plugins are updated now! :partying_face:  the last thing to do is to release a new postcss-preset-env version.
For that **the postcss-preset-env plugin definition itself needs to be updated!** (https://github.com/csstools/postcss-preset-env/blob/next/release/src/postcss.js#L11).

@jonathantneal and I will meet next week again. In the meantime we'd welcome a PR which completes the work on the `next/release` branch as mentioned, so that we can quickly release the final postcss8 compatibility next week! Thank you.

**Comment by Antonio-Laguna** [comment] 2021-09-22 15:26
Thanks a lot @dargmuesli and @jonathantneal ! I'm going to get started on that PR ASAP and will update here.

**Comment by Airkro** [comment] 2021-09-24 09:57
Please considering turn off all the plugins that `require JS` by default.

**Comment by dargmuesli** [comment] 2021-10-10 21:58
A new release of https://github.com/shellscape/postcss-values-parser was necessary, which was just created. I proposed the next meeting for the new week in which we could finish our work.

**Comment by dargmuesli** [comment] 2021-11-13 12:20
Hey guys, just want to let you know that @romainmenke and @Antonio-Laguna are now working on the finishing touches and are waiting for feedback and approval of their contributions from Jonathan. For details see the Discord mentioned above.

Still, we're so close to the goal! I think my job is done here, fingers crossed for the remaining bits to settle.
\- Jonas

**Comment by Antonio-Laguna** [comment] 2021-11-16 12:39
Closed with #220 ! Thanks to all

**Closed by Antonio-Laguna** 2021-11-16 12:39 UTC
Labels: help wanted
